In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('DataSource/BL-Flickr-Images-Book.csv')
df.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [ ]:
# Lets drop 
# Edition Statement, Corporate Author, Corporate Contributors, 
# Former owner, Engraver, Issuance type and Shelfmarks
# because this is not very descriptive of the books

In [15]:
to_drop = ['Edition Statement',
           'Corporate Author',
           'Corporate Contributors',
           'Former owner',
           'Engraver',
           'Contributors',
           'Issuance type',
           'Shelfmarks']

df.drop(to_drop, inplace=True, axis=1)

In [ ]:
# inplace parameter as True and the axis parameter as 1. 
# This tells Pandas that we want the changes to be made 
# directly in our object and that it should look for 
# the values to be dropped in the columns of the object

In [16]:
df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [18]:
# df.drop(columns=to_drop, inplace=True) 
# This syntax is more intuitive and readable

In [17]:
df['Identifier'].is_unique

True

In [19]:
# A Pandas Index extends the functionality of NumPy arrays 
# to allow for more versatile slicing and labeling. 
# In many cases, it is helpful to use a uniquely valued 
# identifying field of the data as its index.

In [20]:
df = df.set_index('Identifier')

In [21]:
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [22]:
# Unlike primary keys in SQL, a Pandas Index 
# doesn’t make any guarantee of being unique, 
# although many indexing and merging operations 
# will notice a speedup in runtime if it is.

In [23]:
df.loc[206]

Place of Publication                                               London
Date of Publication                                           1879 [1878]
Publisher                                                S. Tinsley & Co.
Title                                   Walter Forbes. [A novel.] By A. A
Author                                                              A. A.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 206, dtype: object

In [24]:
# We can access each record in a straightforward way with loc[]. 
# Although loc[] may not have all that intuitive of a name, 
# it allows us to do label-based indexing, which is 
# the labeling of a row or record without regard to its position

In [25]:
# df.set_index('Identifier', inplace=True)
# change the index without reassigning to a new object

In [26]:
df.get_dtype_counts()

object    6
dtype: int64

In [27]:
df.loc[1905:, 'Date of Publication'].head(10)

Identifier
1905           1888
1929    1839, 38-54
2836           1897
2854           1865
2956        1860-63
2957           1873
3017           1866
3131           1899
4598           1814
4884           1820
Name: Date of Publication, dtype: object

In [32]:
extr = df['Date of Publication'].str.extract(r'^(\d{4})', expand=False)

In [29]:
extr.head()

Identifier
206    1879
216    1868
218    1869
472    1851
480    1857
Name: Date of Publication, dtype: object

In [30]:
# clean Date of publication to only contain 4 digit year

In [31]:
# this column still has object dtype, 
# but we can easily get its numerical version with pd.to_numeric

In [33]:
df['Date of Publication'] = pd.to_numeric(extr)
df['Date of Publication'].dtype

dtype('float64')

In [34]:
df['Date of Publication'].isnull().sum() / len(df)

0.11717147339205986

In [35]:
# This results in about one in every ten values
# being missing, which is a small price to pay 
# for now being able to do computations on 
# the remaining valid values

In [37]:
# df['Date of Publication'].str -> speeds up operations 
# in Pandas that largely mimic operations on 
# native Python strings or compiled regular 
# expressions, such as .split(), .replace(), and .capitalize()

In [38]:
# To clean the Place of Publication field, 
# we can combine Pandas str methods with NumPy’s np.where function

In [39]:
# np.where(condition, then, else) --> this can be chained

In [40]:
df['Place of Publication'].head(10)

Identifier
206                                  London
216                London; Virtue & Yorston
218                                  London
472                                  London
480                                  London
481                                  London
519                                  London
667     pp. 40. G. Bryan & Co: Oxford, 1898
874                                 London]
1143                                 London
Name: Place of Publication, dtype: object

In [41]:
df.loc[4157862]

Place of Publication                                  Newcastle-upon-Tyne
Date of Publication                                                  1867
Publisher                                                      T. Fordyce
Title                   Local Records; or, Historical Register of rema...
Author                      FORDYCE, T. - Printer, of Newcastle-upon-Tyne
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 4157862, dtype: object

In [42]:
df.loc[4159587]

Place of Publication                                  Newcastle upon Tyne
Date of Publication                                                  1834
Publisher                                                Mackenzie & Dent
Title                   An historical, topographical and descriptive v...
Author                                              Mackenzie, E. (Eneas)
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 4159587, dtype: object

In [44]:
# the above contain same place of publication
# one with hypen another one does not contain hypen

In [45]:
# To clean this column in one sweep, we can use str.contains() to get a boolean mask

In [46]:
pub = df['Place of Publication']

In [47]:
london = pub.str.contains('London')
london[:5]

Identifier
206    True
216    True
218    True
472    True
480    True
Name: Place of Publication, dtype: bool

In [48]:
oxford = pub.str.contains('Oxford')

In [49]:
df['Place of Publication'] = np.where(london, 'London',
                                      np.where(oxford, 'Oxford',
                                               pub.str.replace('-', ' ')))
df['Place of Publication'].head()

Identifier
206    London
216    London
218    London
472    London
480    London
Name: Place of Publication, dtype: object

In [50]:
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [51]:
df.head(100)

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
481,London,1875.0,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
519,London,1872.0,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
667,Oxford,NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
874,London,1676.0,NaN,"A Warning to the inhabitants of England, and L...",Remaʿ.,http://www.flickr.com/photos/britishlibrary/ta...
1143,London,1679.0,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
1280,Coventry,1802.0,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
1808,Christiania,1859.0,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.",http://www.flickr.com/photos/britishlibrary/ta...
1905,Firenze,1888.0,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...",http://www.flickr.com/photos/britishlibrary/ta...
1929,Amsterdam,1839.0,NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
2836,Savona,1897.0,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.",http://www.flickr.com/photos/britishlibrary/ta...
2854,London,1865.0,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.",http://www.flickr.com/photos/britishlibrary/ta...
2956,Paris,1860.0,NaN,"Géodésie d'une partie de la Haute Éthiopie,...","ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
2957,Paris,1873.0,NaN,[With eleven maps.],"ABBADIE, Antoine Thompson d'.",http://www.flickr.com/photos/britishlibrary/ta...
3017,Puerto Rico,1866.0,NaN,"[Historia geográfica, civil y politica de la ...","ABBAD Y LASIERRA, Agustín Íñigo - Bishop of...",http://www.flickr.com/photos/britishlibrary/ta...
3131,New York,1899.0,W. Abbatt,"The Crisis of the Revolution, being the story ...","ABBATT, William.",http://www.flickr.com/photos/britishlibrary/ta...
4598,Hull,1814.0,The Author,Peace: a lyric poem. [With prefatory address b...,"ABBOTT, Thomas Eastoe.",http://www.flickr.com/photos/britishlibrary/ta...
4884,London,1820.0,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian ...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4976,Oxonii,1800.0,"J. Cooke, etc.",[Abdollatiphi Historiæ Ægypti compendium. [Wit...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
5382,London,1847.0,Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5385,London,NaN,"Bradbury, Agnew & Co.",[The comic history of England ... With twenty ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5389,London,NaN,"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5432,Milano,1893.0,NaN,Signa: opera in tre atti [founded on the novel...,"A'BECKETT, Gilbert Arthur - and RUDALL (H. A.)",http://www.flickr.com/photos/britishlibrary/ta...
6036,London,1805.0,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ......",NaN,http://www.flickr.com/photos/britishlibrary/ta...
6821,Aberdeen,1837.0,J. Davidson & Co.,Description of the Coast between Aberdeen and ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
7521,Wien,1896.0,NaN,Aus Kaukasischen Ländern. Reisebriefe von H. ...,"ABICH, Wilhelm Hermann.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...
29031,London,1827.0,William Carpenter,The Age Reviewed: a satire. [In verse. By Robe...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
29032,London,1828.0,W. C. Wright,[The Age Reviewed: a satire. [In verse. By Rob...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
29285,London,1876.0,Chapman & Hall,Through the Ages. A psychological romance. By ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
29505,A. Millar,1758.0,London,"Agis: a tragedy, etc. [In verse. By John Home.]",NaN,http://www.flickr.com/photos/britishlibrary/ta...
29844,New York,1846.0,"Leavitt, Trow & Co.",The Gem of the Season: with twenty plates by S...,"AGNEW, John Holmes.",http://www.flickr.com/photos/britishlibrary/ta...
30269,Allahabad],1880.0,NaN,Mathurá: a District Memoir. By F. S. Growse ....,NaN,http://www.flickr.com/photos/britishlibrary/ta...
31858,London,1823.0,G. & W. B. Whittaker,"Ahasuerus, the Wanderer; a dramatic legend [in...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
32896,Stuttgart,1887.0,NaN,Skandinavische Hof- und Staatsgeschichten des ...,"AHNFELT, Arvid.",http://www.flickr.com/photos/britishlibrary/ta...
33745,London,1825.0,Longman & Co.,The Works of Anna Lætitia Barbauld. With a mem...,"AIKIN, afterwards BARBAULD, Anna Laetitia.",http://www.flickr.com/photos/britishlibrary/ta...
33833,D. Appleton & Co,1850.0,New York,The Vicar of Wakefield ... Illustrated with nu...,"Goldsmith, Oliver",http://www.flickr.com/photos/britishlibrary/ta...
33881,London,1810.0,R. H. Evans,[Essays on song-writing: with a collection of ...,"AIKIN, John - M.D",http://www.flickr.com/photos/britishlibrary/ta...
34361,Санктпетербургъ,1889.0,NaN,Кіево-Софійскій Соборъ. Изслѣдованіе древней м...,"AINALOV, Dmitry Vlas'evich - and REDIN (Egor K...",http://www.flickr.com/photos/britishlibrary/ta...
34463,London,1872.0,J. Maxwell & Co.,Robert Ainsleigh. By the author of 'Lady Audle...,"AINSLEIGH, Robert.",http://www.flickr.com/photos/britishlibrary/ta...
34538,Paisley,1892.0,Alexander Gardner,"A Pilgrimage to the Land of Burns, and Poems ....","AINSLIE, Hew.",http://www.flickr.com/photos/britishlibrary/ta...
34785,London,NaN,J. Maxwell & Co.,The illustrated universal gazetteer,NaN,http://www.flickr.com/photos/britishlibrary/ta...
34793,London,NaN,C. Griffin & Co.,"Wanderings in every Clime; or, voyages, travel...","AINSWORTH, William Francis.",http://www.flickr.com/photos/britishlibrary/ta...
34810,London,1872.0,Tinsley Bros.,"Boscobel; or, the Royal Oak. A tale of the yea...","Ainsworth, William Harrison",http://www.flickr.com/photos/britishlibrary/ta...
34826,London,1861.0,Chapman & Hall,The Constable of the Tower: an historical roma...,"Ainsworth, William Harrison",http://www.flickr.com/photos/britishlibrary/ta...
34852,London,NaN,G. Routledge & Sons,"[The Flitch of Bacon: or, the Custom of Dunmow...","Ainsworth, William Harrison",http://www.flickr.com/photos/britishlibrary/ta...
34914,London,1858.0,G. Routledge & Co.,Mervyn Clitheroe ... Illustrated by Hablot K. ...,"Ainsworth, William Harrison",http://www.flickr.com/photos/britishlibrary/ta...
34952,London,1860.0,"Routledge, Warne & Routledge",Ovingdean Grange. A tale of the South Downs. I...,"Ainsworth, William Harrison",http://www.flickr.com/photos/britishlibrary/ta...
34967,London,1857.0,G. Routledge & Co.,[Rookwood ... The fourth edition ... with illu...,"Ainsworth, William Harrison",http://www.flickr.com/photos/britishlibrary/ta...
34987,London,1857.0,G. Routledge & Co.,The Spendthrift: a tale ... With illustrations...,"Ainsworth, William Harrison",http://www.flickr.com/photos/britishlibrary/ta...
36171,Paris,NaN,NaN,L'Auvergne. Illustrations de A. Montader,"Ajalbert, Jean",http://www.flickr.com/photos/britishlibrary/ta...
36231,London,1878.0,William Poole,Plimsoll's England. A satire. By Ajax. [In ver...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
36521,Edinburgh,1857.0,James Nichol,[The Poetical Works of Mark Akenside ... With ...,"Akenside, Mark",http://www.flickr.com/photos/britishlibrary/ta...
36531,Napoli,1821.0,NaN,[Hymn to the Naiads.] Alle Najadi. Inno alla G...,"AKENSIDE, Mark.",http://www.flickr.com/photos/britishlibrary/ta...
36721,London,1897.0,Bliss & Sands,Triscombe Stone: a romance of the Quantock Hil...,"AKERMAN, Portland Board - and HURST (Norman)",http://www.flickr.com/photos/britishlibrary/ta...
38673,Ἐν Κερκυρᾳ,1891.0,NaN,Κερκυραϊκα ἀπομνημονευματα. [Edited by I. De...,"ALBANAS, Phriderikos.",http://www.flickr.com/photos/britishlibrary/ta...
38986,London,1827.0,William Marsh,Scenes and Occurrences in Albany and Cafferlan...,NaN,http://www.flickr.com/photos/britishlibrary/ta...